# Generated by Django 5.2.8 on 2025-11-19 12:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('es_nn', models.BooleanField(default=False)),
                ('id_temporal', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('edad_aproximada', models.IntegerField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, help_text='Características físicas para identificación', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('paramedico', 'Paramédico'), ('tens', 'TENS'), ('medico', 'Médico'), ('administrador', 'Administrador')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FichaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('circunstancias', models.TextField()),
                ('sintomas', models.TextField()),
                ('nivel_consciencia', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('en_ruta', 'En Ruta'), ('en_hospital', 'En Hospital'), ('atendido', 'Atendido')], default='en_ruta', max_length=20)),
                ('prioridad', models.CharField(choices=[('C1', 'C1 - Crítico'), ('C2', 'C2 - Emergencia'), ('C3', 'C3 - Urgencia'), ('C4', 'C4 - Urgencia Menor'), ('C5', 'C5 - No Urgente')], max_length=2)),
                ('eta', models.CharField(blank=True, help_text='Tiempo estimado de llegada', max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paramedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_paramedico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='urgencias.paciente')),
            ],
            options={
                'verbose_name': 'Ficha de Emergencia',
                'verbose_name_plural': 'Fichas de Emergencia',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_cie10', models.CharField(help_text='Código CIE-10', max_length=100)),
                ('descripcion', models.TextField()),
                ('indicaciones_medicas', models.TextField()),
                ('medicamentos_prescritos', models.TextField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_realizados', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='urgencias.fichaemergencia')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_enfermedad_actual', models.TextField()),
                ('antecedentes_medicos', models.TextField()),
                ('alergias_medicamentosas', models.JSONField(default=list, help_text='Lista de alergias')),
                ('alergias_criticas', models.BooleanField(default=False)),
                ('medicamentos_habituales', models.TextField(blank=True, null=True)),
                ('antecedentes_quirurgicos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anamnesis_registradas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='urgencias.fichaemergencia')),
            ],
            options={
                'verbose_name': 'Anamnesis',
                'verbose_name_plural': 'Anamnesis',
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_sistolica', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('frecuencia_cardiaca', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('frecuencia_respiratoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('saturacion_o2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('glucosa', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('escala_glasgow', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('eva', models.IntegerField(blank=True, help_text='Escala de dolor 0-10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ubicacion_gps', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='urgencias.fichaemergencia')),
            ],
            options={
                'verbose_name': 'Signos Vitales',
                'verbose_name_plural': 'Signos Vitales',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizado', 'Autorizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_medicamentos', to='urgencias.fichaemergencia')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('paramedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Medicamento',
                'verbose_name_plural': 'Solicitudes de Medicamentos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
