# Generated by Django 5.2.8 on 2025-11-23 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(help_text='Tipo de examen solicitado', max_length=200)),
                ('examenes_especificos', models.TextField(help_text='Lista detallada de exámenes')),
                ('justificacion', models.TextField(help_text='Justificación clínica')),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente'), ('normal', 'Normal'), ('diferido', 'Diferido')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_examenes', to='urgencias.fichaemergencia')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Examen',
                'verbose_name_plural': 'Solicitudes de Exámenes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
