# Generated by Django 5.2.8 on 2025-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0002_solicitudexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad médica o profesional', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='registro_profesional',
            field=models.CharField(blank=True, help_text='Número de registro profesional', max_length=50, null=True),
        ),
    ]
