# Generated by Django 5.2.8 on 2025-11-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0002_solicitudexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_ficha', 'Nueva Ficha de Emergencia'), ('solicitud_medicamento', 'Solicitud de Medicamento'), ('solicitud_examen', 'Solicitud de Examen'), ('cambio_estado', 'Cambio de Estado de Ficha'), ('signos_vitales', 'Nuevos Signos Vitales'), ('diagnostico', 'Nuevo Diagnóstico'), ('alta_medica', 'Alta Médica')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, null=True)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='urgencias.fichaemergencia')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario_destinatario', '-fecha_creacion'], name='urgencias_n_usuario_e8d1c0_idx'), models.Index(fields=['usuario_destinatario', 'leida'], name='urgencias_n_usuario_cd2d67_idx')],
            },
        ),
    ]
