# Generated by Django 5.2.8 on 2025-11-24 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0003_usuario_especialidad_usuario_registro_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('autorizar', 'Autorizar'), ('rechazar', 'Rechazar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión')], max_length=20)),
                ('modelo', models.CharField(help_text='Modelo afectado (ej: FichaEmergencia, Usuario)', max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('detalles', models.JSONField(blank=True, help_text='Detalles adicionales de la acción', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='urgencias_a_timesta_1ca4bb_idx'), models.Index(fields=['usuario', '-timestamp'], name='urgencias_a_usuario_20b6b4_idx'), models.Index(fields=['modelo', '-timestamp'], name='urgencias_a_modelo_86696f_idx')],
            },
        ),
    ]
