# Generated by Django 5.2.8 on 2025-11-24 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camas_totales', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('camas_uci', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('salas_emergencia', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('boxes_atencion', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Hospital',
                'verbose_name_plural': 'Configuraciones del Hospital',
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número o código de la cama', max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('uci', 'UCI'), ('emergencia', 'Emergencia')], default='general', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'En Limpieza')], default='disponible', max_length=20)),
                ('piso', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('ficha_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cama_asignada', to='urgencias.fichaemergencia')),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
                'ordering': ['tipo', 'numero'],
                'indexes': [models.Index(fields=['estado', 'tipo'], name='urgencias_c_estado_ce382a_idx'), models.Index(fields=['numero'], name='urgencias_c_numero_c365dd_idx')],
            },
        ),
    ]
