# Generated by Django 5.2.8 on 2025-11-26 01:35

import django.db.models.deletion
import urgencias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0005_configuracionhospital_cama'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=urgencias.models.archivo_upload_path)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('pdf', 'PDF'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('tamano', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='urgencias.fichaemergencia')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('archivo_adjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='urgencias.archivoadjunto')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='urgencias.fichaemergencia')),
                ('leido_por', models.ManyToManyField(blank=True, related_name='mensajes_leidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha_envio'],
                'indexes': [models.Index(fields=['ficha', 'fecha_envio'], name='urgencias_m_ficha_i_216483_idx')],
            },
        ),
    ]
