# Generated by Django 5.2.8 on 2025-11-26 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0006_archivoadjunto_mensajechat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_ficha', 'Nueva Ficha de Emergencia'), ('ficha_llegada', 'Paciente Llegó al Hospital'), ('solicitud_medicamento', 'Solicitud de Medicamento'), ('medicamento_autorizado', 'Medicamento Autorizado'), ('medicamento_rechazado', 'Medicamento Rechazado'), ('nuevos_signos', 'Nuevos Signos Vitales'), ('diagnostico', 'Nuevo Diagnóstico'), ('mensaje_chat', 'Nuevo Mensaje'), ('examen_solicitado', 'Examen Solicitado'), ('cama_asignada', 'Cama Asignada'), ('alta_paciente', 'Alta de Paciente'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='urgencias.fichaemergencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='urgencias_n_usuario_ffe27e_idx'), models.Index(fields=['usuario', 'fecha_creacion'], name='urgencias_n_usuario_72fc48_idx')],
            },
        ),
    ]
