# Generated by Django 5.2.8 on 2025-11-26 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='glasgow_motor',
            field=models.IntegerField(default=6, help_text='Respuesta motora (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='glasgow_ocular',
            field=models.IntegerField(default=4, help_text='Respuesta ocular (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='glasgow_verbal',
            field=models.IntegerField(default=5, help_text='Respuesta verbal (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='signosvitales',
            name='escala_glasgow',
            field=models.IntegerField(blank=True, help_text='Calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
