# Generated by Django 5.2.8 on 2025-11-26 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0008_add_glasgow_components'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='urgencias_n_usuario_cd2d67_idx',
            old_name='urgencias_n_usuario_ffe27e_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='urgencias_n_usuario_56d626_idx',
            old_name='urgencias_n_usuario_72fc48_idx',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_leida',
            field=models.DateTimeField(blank=True, db_column='fecha_lectura', null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_destinatario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
