# Generated by Django 5.2.8 on 2025-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0009_rename_urgencias_n_usuario_ffe27e_idx_urgencias_n_usuario_cd2d67_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='acompanante_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='acompanante_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(blank=True, choices=[('FONASA A', 'FONASA A'), ('FONASA B', 'FONASA B'), ('FONASA C', 'FONASA C'), ('FONASA D', 'FONASA D'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'Particular'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
