# Generated by Django 5.2.8 on 2025-11-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0010_paciente_acompanante_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='codigo_diagnostico',
            field=models.CharField(blank=True, help_text='Código único auto-generado DX-YYYYMMDD-XXXX', max_length=20, null=True, unique=True),
        ),
    ]
