# Generated by Django 5.2.8 on 2025-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0011_diagnostico_codigo_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaemergencia',
            name='estado',
            field=models.CharField(choices=[('en_ruta', 'En Ruta'), ('en_hospital', 'En Hospital'), ('atendido', 'Atendido'), ('dado_de_alta', 'Dado de Alta')], default='en_ruta', max_length=20),
        ),
    ]
