# Generated by Django 5.2.8 on 2025-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0012_alter_fichaemergencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='destino_derivacion',
            field=models.CharField(blank=True, help_text='Hospital o especialista destino si es derivación', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='hora_fallecimiento',
            field=models.DateTimeField(blank=True, help_text='Hora de fallecimiento si aplica', null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='tipo_alta',
            field=models.CharField(choices=[('domicilio', 'Alta a Domicilio'), ('hospitalizacion', 'Hospitalización'), ('uci', 'Ingreso a UCI'), ('derivacion', 'Derivación a Especialista'), ('voluntaria', 'Alta Voluntaria'), ('fallecido', 'Fallecido')], default='domicilio', max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaemergencia',
            name='estado',
            field=models.CharField(choices=[('en_ruta', 'En Ruta'), ('en_hospital', 'En Hospital'), ('atendido', 'Atendido'), ('dado_de_alta', 'Dado de Alta'), ('hospitalizado', 'Hospitalizado'), ('uci', 'UCI'), ('derivado', 'Derivado'), ('fallecido', 'Fallecido')], default='en_ruta', max_length=20),
        ),
    ]
