# Generated by Django 5.2.8 on 2025-11-26 16:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0013_diagnostico_destino_derivacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('nueva_ficha', 'Nueva Ficha de Emergencia'), ('ficha_llegada', 'Paciente Llegó al Hospital'), ('solicitud_medicamento', 'Solicitud de Medicamento'), ('medicamento_autorizado', 'Medicamento Autorizado'), ('medicamento_rechazado', 'Medicamento Rechazado'), ('nuevos_signos', 'Nuevos Signos Vitales'), ('signos_criticos', 'Signos Vitales Críticos'), ('diagnostico', 'Nuevo Diagnóstico'), ('mensaje_chat', 'Nuevo Mensaje'), ('examen_solicitado', 'Examen Solicitado'), ('examen_completado', 'Examen Completado'), ('triage_completado', 'Triage Completado'), ('cama_asignada', 'Cama Asignada'), ('alta_paciente', 'Alta de Paciente'), ('hospitalizacion', 'Paciente Hospitalizado'), ('ingreso_uci', 'Ingreso a UCI'), ('derivacion', 'Paciente Derivado'), ('fallecimiento', 'Fallecimiento'), ('tiempo_espera', 'Alerta Tiempo de Espera'), ('sistema', 'Notificación del Sistema')], max_length=30),
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_esi', models.IntegerField(choices=[(1, 'ESI 1 - Resucitación (inmediato)'), (2, 'ESI 2 - Emergencia (< 10 min)'), (3, 'ESI 3 - Urgencia (< 30 min)'), (4, 'ESI 4 - Menos urgente (< 60 min)'), (5, 'ESI 5 - No urgente (< 120 min)')], help_text='Nivel de gravedad ESI 1-5')),
                ('color_manchester', models.CharField(blank=True, choices=[('rojo', 'Rojo - Inmediato'), ('naranja', 'Naranja - Muy Urgente'), ('amarillo', 'Amarillo - Urgente'), ('verde', 'Verde - Normal'), ('azul', 'Azul - No Urgente')], max_length=10, null=True)),
                ('motivo_consulta_triage', models.TextField(help_text='Motivo de consulta según el paciente/acompañante')),
                ('tiempo_inicio_sintomas', models.CharField(blank=True, help_text='Ej: 2 horas, 3 días', max_length=100, null=True)),
                ('via_aerea', models.CharField(choices=[('permeable', 'Permeable'), ('comprometida', 'Comprometida'), ('obstruida', 'Obstruida')], default='permeable', max_length=20)),
                ('respiracion_normal', models.BooleanField(default=True)),
                ('circulacion_normal', models.BooleanField(default=True)),
                ('estado_consciencia', models.CharField(help_text='Alerta, Responde a voz, Responde a dolor, No responde (AVDN)', max_length=100)),
                ('dolor_presente', models.BooleanField(default=False)),
                ('escala_dolor', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('localizacion_dolor', models.CharField(blank=True, max_length=200, null=True)),
                ('fiebre_alta', models.BooleanField(default=False, help_text='Temperatura > 38.5°C')),
                ('dificultad_respiratoria', models.BooleanField(default=False)),
                ('dolor_toracico', models.BooleanField(default=False)),
                ('alteracion_neurologica', models.BooleanField(default=False)),
                ('sangrado_activo', models.BooleanField(default=False)),
                ('trauma_mayor', models.BooleanField(default=False)),
                ('recursos_necesarios', models.IntegerField(default=0, help_text='Número estimado de recursos/procedimientos')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_triage', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='urgencias.fichaemergencia')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Triage',
                'verbose_name_plural': 'Triages',
                'ordering': ['-fecha_triage'],
            },
        ),
    ]
