# Generated by Django 5.2.8 on 2025-11-26 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0014_alter_notificacion_tipo_triage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaemergencia',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cama',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('mantenimiento', 'En Mantenimiento'), ('limpieza', 'En Limpieza')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='cama',
            name='tipo',
            field=models.CharField(choices=[('box', 'Box de Atención'), ('camilla', 'Camilla'), ('cama_general', 'Cama General'), ('cama_uci', 'Cama UCI'), ('sala_emergencia', 'Sala de Emergencia'), ('sala_espera', 'Sala de Espera')], default='general', max_length=20),
        ),
    ]
