# Generated by Django 5.2.8 on 2025-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0015_fichaemergencia_medico_asignado_alter_cama_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='duracion',
            field=models.FloatField(blank=True, help_text='Duración en segundos para audio/video', null=True),
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniatura para videos', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20),
        ),
    ]
