# Generated by Django 5.2.8 on 2025-11-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0016_archivoadjunto_duracion_archivoadjunto_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evolucion', 'Nota de Evolución'), ('interconsulta', 'Interconsulta'), ('procedimiento', 'Procedimiento'), ('enfermeria', 'Nota de Enfermería'), ('cambio_tratamiento', 'Cambio de Tratamiento'), ('evento_adverso', 'Evento Adverso'), ('traslado', 'Traslado')], default='evolucion', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('subjetivo', models.TextField(blank=True, help_text='Lo que el paciente refiere (síntomas, molestias, cómo se siente)')),
                ('objetivo', models.TextField(blank=True, help_text='Hallazgos del examen físico, signos vitales, resultados de exámenes')),
                ('analisis', models.TextField(blank=True, help_text='Interpretación clínica, evolución del diagnóstico, problemas identificados')),
                ('plan', models.TextField(blank=True, help_text='Plan terapéutico, indicaciones, exámenes a solicitar')),
                ('signos_vitales', models.JSONField(blank=True, help_text='Signos vitales al momento de la nota: {pa_sistolica, pa_diastolica, fc, fr, temp, sat_o2}', null=True)),
                ('glasgow', models.IntegerField(blank=True, help_text='Escala de Glasgow (3-15)', null=True)),
                ('indicaciones_actualizadas', models.TextField(blank=True, help_text='Nuevas indicaciones o modificaciones al tratamiento')),
                ('medicamentos_actualizados', models.TextField(blank=True, help_text='Cambios en medicamentos')),
                ('editado', models.BooleanField(default=False)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('motivo_edicion', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evolucion', to='urgencias.fichaemergencia')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_evolucion_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Evolución',
                'verbose_name_plural': 'Notas de Evolución',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['ficha', 'fecha_hora'], name='urgencias_n_ficha_i_1805c9_idx'), models.Index(fields=['medico', 'fecha_hora'], name='urgencias_n_medico__3797be_idx')],
            },
        ),
    ]
