# Generated by Django 5.2.8 on 2025-11-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0017_add_nota_evolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AM', 'Turno AM (Día)'), ('PM', 'Turno PM (Noche)'), ('DOBLE', 'Turno Doble (24h)')], max_length=10, unique=True)),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(help_text='Hora de fin del turno')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Turno',
                'verbose_name_plural': 'Configuraciones de Turnos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del turno')),
                ('tipo_turno', models.CharField(choices=[('AM', 'Turno AM (Día)'), ('PM', 'Turno PM (Noche)'), ('DOBLE', 'Turno Doble (24h)'), ('DESCANSO', 'Descanso')], max_length=10)),
                ('en_turno', models.BooleanField(default=False, help_text='Si el usuario está actualmente trabajando')),
                ('hora_entrada', models.DateTimeField(blank=True, help_text='Hora real de entrada', null=True)),
                ('hora_salida', models.DateTimeField(blank=True, help_text='Hora real de salida', null=True)),
                ('es_voluntario', models.BooleanField(default=False, help_text='Si es un turno voluntario sin asignación previa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del turno', null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', 'usuario__first_name'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='unique_turno_usuario_fecha')],
            },
        ),
    ]
