# Generated by Django 5.2.8 on 2025-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0018_configuracionturno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaemergencia',
            name='fecha_llegada_hospital',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de llegada al hospital', null=True),
        ),
        migrations.AlterField(
            model_name='cama',
            name='tipo',
            field=models.CharField(choices=[('box', 'Box'), ('uci', 'UCI'), ('uti', 'UTI'), ('cama_general', 'Cama General')], default='cama_general', max_length=20),
        ),
    ]
