# Generated by Django 5.2.8 on 2025-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urgencias', '0019_add_fecha_llegada_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='tipo',
            field=models.CharField(choices=[('box', 'Box de Atención'), ('hospitalizacion', 'Hospitalización'), ('uci', 'UCI')], default='cama_general', max_length=20),
        ),
    ]
